Tl: true
img_quality: 100
tl_priority: -999
show_all_bindings: true
tl_render_mode: single
tl_merge_uids_per_image: 5
tl_uids_per_image: 2
tl_cards_per_msg: 3
all_abyss: true
all_abyss_render_mode: desktop
